# Generated by Django 6.0.3 on 2026-03-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workout_location',
            field=models.CharField(blank=True, choices=[('HOME', 'Home (Calisthenics)'), ('GYM', 'Gym')], max_length=4, null=True),
        ),
    ]
