# Generated by Django 6.0.3 on 2026-03-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_workoutlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='rest_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط صورة التمرين'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'خامل (مكتب)'), ('light', 'نشاط خفيف (تمرين 1-3 أيام)'), ('moderate', 'نشاط متوسط (تمرين 3-5 أيام)'), ('active', 'نشاط عالي (تمرين يومي)')], default='moderate', max_length=20, verbose_name='مستوى النشاط'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('Beginner', 'مبتدئ'), ('Intermediate', 'متوسط'), ('Advanced', 'متقدم')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='location',
            field=models.CharField(choices=[('HOME', 'البيت'), ('GYM', 'الجيم')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم التمرين'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(verbose_name='العدات المستهدفة'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(verbose_name='المجموعات المستهدفة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', max_length=1, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(verbose_name='الطول (سم)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(verbose_name='الوزن (كجم)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workout_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
