# Generated by Django 6.0.3 on 2026-03-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_remove_exercise_rest_time_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('PUSH', 'Push (صدر، كتف، تراي)'), ('PULL', 'Pull (ظهر، باي، ساعد)'), ('LEGS', 'Legs (أرجل)'), ('CORE', 'Core (بطن وجذع)')], default='PUSH', max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(),
        ),
    ]
